apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reservation-prod
resources:
- secret.yaml
- ../../../base/be









patches:
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: api.reservation.scg.skku.ac.kr

    - op: replace
      path: /spec/rules/0/host
      value: api.reservation.scg.skku.ac.kr

    - op: replace
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-origin
      value: "https://semi.room.scg.skku.ac.kr"
  target:
    kind: Ingress
    name: reservation-be-ingress
images:
- name: scgskku/reservation-be
  newName: scgskku/reservation-be-prod
- name: scgskku/reservation-be-prod
  newTag: 5d1a1d18cf97a51558daf84e2c601490d206e472-26444060712-1
