apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reservation-dev
resources:
- namespace.yaml
- secret.yaml
- ../../../base/be

      





patches:
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: reservation-dev.scg.skku.ac.kr

    - op: replace
      path: /spec/rules/0/host
      value: reservation-dev.scg.skku.ac.kr

    - op: replace
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-origin
      value: https://reservation-dev.scg.skku.ac.kr
  target:
    kind: Ingress
    name: reservation-be-ingress

images:
- name: scgskku/reservation-be
  newName: scgskku/reservation-be-dev
- name: scgskku/reservation-be-dev
  newTag: fe53f0f904611d563b4b7f2a697f76a55823ff7d-23042043835-1
