apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reservation-dev
resources:
- secret.yaml
- ../../../base/be



patches:
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: api.reservation-dev.scg.skku.ac.kr

    - op: replace
      path: /spec/rules/0/host
      value: api.reservation-dev.scg.skku.ac.kr

    - op: replace
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-origin
      value: "https://reservation-dev.scg.skku.ac.kr, https://api.reservation-dev.scg.skku.ac.kr"
  target:
    kind: Ingress
    name: reservation-be-ingress

images:
- name: scgskku/reservation-be
  newName: scgskku/reservation-be-dev
- name: scgskku/reservation-be-dev
  newTag: 49870389a1d19cafec78b06292be707bfcc2bd20-24071752289-1
