apiVersion: v1
kind: Secret
metadata:
  name: reservation-secret
  annotations:
    avp.kubernetes.io/path: kv/data/reservation-dev-secret
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: dev
  SWAGGER_ID: <path:kv/data/reservation-dev-secret#swagger-id>
  SWAGGER_PASSWORD: <path:kv/data/reservation-dev-secret#swagger-password>