apiVersion: v1
kind: Secret
metadata:
  name: reservation-secret
  annotations:
    avp.kubernetes.io/path: kv/data/reservation-dev-secret
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: dev
  SWAGGER_ID: <path:kv/data/reservation-dev-secret#swagger-id>
  SWAGGER_PASSWORD: <path:kv/data/reservation-dev-secret#swagger-password>
  DB_URL: <path:kv/data/reservation-dev-secret#db-url>
  DB_USERNAME: <path:kv/data/reservation-dev-secret#db-username>
  DB_PASSWORD: <path:kv/data/reservation-dev-secret#db-password>
  GOOGLE_CLIENT_ID: <path:kv/data/reservation-dev-secret#google-client-id>
  GOOGLE_CLIENT_SECRET: <path:kv/data/reservation-dev-secret#google-client-secret>
  GOOGLE_CALLBACK_URI: <path:kv/data/reservation-dev-secret#google-callback-uri>
  JWT_SECRET: <path:kv/data/reservation-dev-secret#jwt-secret>