apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reservation-prod
resources:
- secret.yaml
- ../../../base/fe


patches:
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: semi.room.scg.skku.ac.kr

    - op: replace
      path: /spec/rules/0/host
      value: semi.room.scg.skku.ac.kr
  target:
    kind: Ingress
    name: reservation-fe-ingress
images:
- name: scgskku/reservation-fe-prod
  newTag: eebb30f0725df46725ba48b60843c143d1621bfe-24310215546-1
