apiVersion: v1
kind: Secret
metadata:
  name: reservation-fe-secret
  annotations:
    avp.kubernetes.io/path: kv/data/reservation-prod-secret
type: Opaque
stringData:
  NEXT_PUBLIC_API_URL: https://api.reservation.scg.skku.ac.kr
