apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reservation-dev
resources:
- secret.yaml
- ../../../base/fe

patches:
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: reservation-dev.scg.skku.ac.kr

    - op: replace
      path: /spec/rules/0/host
      value: reservation-dev.scg.skku.ac.kr
  target:
    kind: Ingress
    name: reservation-fe-ingress

images:
- name: scgskku/reservation-fe
  newName: scgskku/reservation-fe-dev
- name: scgskku/reservation-fe-dev
  newTag: 96af41ddc04c2e0fbc5445b6a0c1e69932e0d2d3-24440706423-1
