apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reservation-dev
resources:
- secret.yaml
- ../../../base/fe






















patches:
- patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: reservation-dev.scg.skku.ac.kr

    - op: replace
      path: /spec/rules/0/host
      value: reservation-dev.scg.skku.ac.kr
  target:
    kind: Ingress
    name: reservation-fe-ingress

images:
- name: scgskku/reservation-fe
  newName: scgskku/reservation-fe-dev
- name: scgskku/reservation-fe-dev
  newTag: 279c6d248032ba59c684dd6282ce2a547a2b495f-24234934269-1
