apiVersion: v1
kind: Secret
metadata:
  name: reservation-fe-secret
  annotations:
    avp.kubernetes.io/path: kv/data/reservation-dev-secret
type: Opaque
stringData:
  NEXT_PUBLIC_API_URL: <path:kv/data/reservation-dev-secret#next-public-api-url>
